platform :android do
  desc "Pull Request verification"
  lane :ci do
    gradle(task: "detekt lintDebug jacocoTestReport")
    gradle(task: "android:sample:assembleDebug android:sample:assembleDebugAndroidTest")
    codecov_reporter
  end

  desc "Deploy new version"
  lane :ci_deploy do
     sh "bash ./publishRemote.sh"
     set_github_release(
       repository_name: "ZupIT/beagle",
       api_token: ENV["REPO_TOKEN"],
       name: git_branch,
       tag_name: git_branch,
       description: release_notes,
       commitish: "master")
  end

end

desc "Generate release notes"
  private_lane :release_notes do
    version_number = git_branch
    changelog = changelog_from_git_commits(
                        merge_commit_filtering: "exclude_merges",
                        pretty: "%s - (%ae %aD)")

    "\nRelease notes #{version_number}
    \nChanges:
    \n#{changelog}"
  end