platform :android do
  desc "Pull Request verification"
  lane :ci do
    gradle(task: "detekt lintDebug jacocoTestReport")
    gradle(task: "android:sample:assembleDebug android:sample:assembleDebugAndroidTest")
    codecov_reporter(token: ENV["CODECOV_TOKEN"])
  end

  desc "Deploy remote new version"
  lane :ci_deploy do
    gradle(task: "build")
    gradle(task: "publish")
  end

   desc "Deploy local new version"
    lane :ci_local_deploy do
      gradle(task: "build")
      gradle(task: "publishToMavenLocal")
    end

end

desc "Generate new release"
  lane :deploy_new_version do
    git_pull(only_tags: true)
    ENV["VERSION_DEPLOY"] = last_git_tag
    #sh "fastlane android ci_deploy"

     sh "bash ./delete_release.sh"
     set_github_release(
       repository_name: "ZupIT/beagle-closed",
       api_token: ENV["REPO_TOKEN"],
       name: ENV["VERSION_DEPLOY"],
       tag_name: ENV["VERSION_DEPLOY"],
       description: release_notes,
       commitish: "master")

  end

desc "Generate release notes"
  private_lane :release_notes do
    most_recent_tags = sh("git tag | sort -r | head -2").split("\n")
    changelog = changelog_from_git_commits(
                        between: most_recent_tags,
                        merge_commit_filtering: "exclude_merges",
                        pretty: "%s - (%ae %aD)")

    "\nRelease notes #{ ENV["VERSION_DEPLOY"] }
    \nChanges:
    \n#{changelog}"
  end


###
###  iOS
###

platform :ios do
  desc "Lane for CI"
  lane :ci do 
    init_dependencies
    scan(
      workspace: "iOS/Darwin-BeagleUI.xcworkspace/",
      scheme: "BeagleUI",
      device: "iPhone 11"
    )
    codecov_reporter(token: ENV["CODECOV_TOKEN"])
  end
end

desc "Dependency Manager (Carthage) https://docs.fastlane.tools/actions/carthage/"
private_lane :init_dependencies do
  carthage(
    command: "bootstrap",
    verbose: true,
    platform: "iOS",
    project_directory: "iOS/Sources/BeagleUI/", cache_builds: true
  )
end